graphhopper:
  datareader.file: turkmenistan-latest.osm.pbf
  graph.location: /app/graph-cache

  profiles:
    - name: car
      custom_model_files: [car.json]

  profiles_ch:
    - profile: car

  profiles_lm: []

  graph.encoded_values: car_access, car_average_speed, road_access

  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

  routing.non_ch.max_waypoint_distance: 1000000

  import.osm.ignored_highways: footway,construction,cycleway,path,steps

  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
