graphhopper:
  datareader.file: turkmenistan-latest.osm.pbf
  graph.location: graph-cache
  profiles:
    - name: car
      vehicle: car
      weighting: fastest
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: bike
      vehicle: bike
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
